services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    develop:
      watch:
      - action: sync
        path : ./
        target: /src
        ignore:
          - node_modules/
      - action: rebuild
        path: ./
        target: /src
        ignore:
          - node_modules/
    command: npm start
